#!/usr/bin/env bash
# prepare-ui-swap.sh — optional ZEC prepared-service acceptance exercise.
#
# Models the repository's M6 lane (run-m2-taker-sells-lez-poc.sh with
# M6_TAKER_SERVICE_MODE=1) and the zec_chat_process.rs service test:
# provisions the deterministic local ZEC corridor fixture, restarts the maker
# daemon with its real Chat authority, publishes a ZEC offer, prepares the
# taker's unsigned draft + actor source, and rewrites the Taker Node
# configuration with a prepared entry (execute_prepared_zec: true).
#
# This is not the M3 BTC chain demo. After this runs once, the secondary
# Basecamp prepared-corridor journey is real through actor provisioning:
#   Browse authenticated offers -> review -> "Confirm and initiate"
# performs the REAL Maker Chat propose/complete and durable actor
# provisioning (state NotActivated; chain effects remain actor work).
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

# Reuse the environment generated by scripts/up.sh so the demo command works
# from a fresh shell as documented.
if [[ -f runtime/runtime.env ]]; then
  set -a
  source runtime/runtime.env
  set +a
fi

TOKEN="ui$(date -u +%m%d%H%M%S)-$$"
SWAP_ID="${TOKEN}-swap"
OFFER_ID="offer-${TOKEN}-zec"
RESERVATION_ID="reserve-${TOKEN}"
DIRECTION_CLI="${UI_SWAP_DIRECTION:-taker-sells-lez}"
DIRECTION_JSON="TakerSellsLez"
DIRECTION_SPEC="taker_sells_lez"
# Exact amounts encoded by zec-ui-fixture's deterministic agreement.
FOREIGN_UNITS=10000
LEZ_UNITS=25000
TTL=7200
MAKER_ACCOUNT="B1UN3hPgxacgHKBRoThcAmsPajGcUf6YXUhgB36x4DAd"
TAKER_ACCOUNT="34Kqgek6R7N1zU5FSJz8ziXwSPEPCuWGcn1T7GCVrfib"

log() { printf '[prep %s] %s\n' "$TOKEN" "$*"; }
compose() { docker compose "$@"; }

# ---------------------------------------------------------------- 1. fixture
log "provisioning deterministic ZEC corridor fixture"
compose run --rm --no-deps --entrypoint bash maker-node -c "
set -e
mkdir -p /prep/${TOKEN}
chmod 0700 /prep/${TOKEN}
rm -rf /prep/${TOKEN}/actors
/usr/local/bin/zec-ui-fixture --output-root /prep/${TOKEN}/actors --swap-id ${SWAP_ID} \
  --valid-for-seconds ${TTL} > /prep/${TOKEN}/fixture-summary.json
"
AGREEMENT="/prep/${TOKEN}/actors/shared/agreement-v2.borsh"
log "fixture provisioned (agreement at ${AGREEMENT})"

# --------------------------------------------------- 2. Maker Node: Chat on
log "enabling the Maker Node ZEC Chat authority"
PROG_SHA="$(compose run --rm --no-deps --entrypoint bash maker-node -c '
if [ ! -f /prep/actor-program ]; then cp /usr/bin/true /prep/actor-program && chmod 0555 /prep/actor-program; fi
sha256sum /prep/actor-program' | tail -1 | cut -d' ' -f1)"
CLAIM_KEY_ID="$(compose run --rm --no-deps --entrypoint bash maker-node -c '
set -e
if [ ! -s /prep/maker-claim-key-id ]; then
  existing="$(grep -aoE "ui-zec-claim-ui[0-9]{10}-[0-9]+" /var/lib/lez/maker/maker.sqlite3 2>/dev/null | head -1 || true)"
  printf "%s\n" "${existing:-ui-zec-claim-local}" > /prep/maker-claim-key-id
  chmod 0600 /prep/maker-claim-key-id
fi
cat /prep/maker-claim-key-id' | tail -1)"
compose stop maker-node >/dev/null
compose run --rm --no-deps --entrypoint bash maker-node -c "
set -e
mkdir -p /prep/${TOKEN}/maker-actors
chmod 700 /prep/${TOKEN}/maker-actors
# The authenticated Delivery identity is also the Maker Zcash agreement key.
# Pin the local-only daemon to the deterministic fixture key before publishing.
cp /prep/${TOKEN}/actors/maker/zcash.key /var/lib/lez/maker/delivery-signing.key
chmod 0600 /var/lib/lez/maker/delivery-signing.key
# Advertisements signed by a previous local identity cannot be reconciled.
find /delivery -maxdepth 1 -type f -name '*.offer.json' -delete
# Strict versioned daemon configuration consumed directly by Rust. Publish by
# atomic rename so a restart cannot observe a partially written argument set.
cat > /prep/maker-node.json.partial <<EOF
{
  \"schema_version\": 1,
  \"arguments\": [
    \"--socket\", \"/run/lez/maker/node.sock\",
    \"--database\", \"/var/lib/lez/maker/maker.sqlite3\",
    \"--ready-file\", \"/run/lez/maker/ready\",
    \"--delivery-directory\", \"/delivery\",
    \"--delivery-signing-key-file\", \"/var/lib/lez/maker/delivery-signing.key\",
    \"--chat-socket\", \"/run/lez/maker/chat.sock\",
    \"--maker-claim-key-id\", \"${CLAIM_KEY_ID}\",
    \"--maker-claim-key-file\", \"/prep/${TOKEN}/actors/maker/claim-recovery.key\",
    \"--maker-claim-preimage-file\", \"/prep/${TOKEN}/actors/maker/claim-preimage.key\",
    \"--zec-source-maker-config\", \"/prep/${TOKEN}/actors/maker/actor-config.json\",
    \"--zec-maker-actor-root\", \"/prep/${TOKEN}/maker-actors\",
    \"--zec-actor-program\", \"/prep/actor-program\",
    \"--zec-actor-program-sha256\", \"${PROG_SHA}\"
  ]
}
EOF
chmod 0600 /prep/maker-node.json.partial
mv -f /prep/maker-node.json.partial /prep/maker-node.json
" >/dev/null
compose up -d maker-node >/dev/null
maker_ready=0
for i in $(seq 1 40); do
  if compose exec -T maker-node lez-maker-cli --socket /run/lez/maker/node.sock health >/dev/null 2>&1; then
    maker_ready=1
    break
  fi
  sleep 1
done
[[ "$maker_ready" == 1 ]] || { compose logs --tail 40 maker-node >&2; exit 1; }
log "Maker Node is back with Chat authority"

# --------------------------------------------------------- 3. publish offer
log "publishing the ZEC offer"
CLI=(compose exec -T maker-node lez-maker-cli --socket /run/lez/maker/node.sock)
rev=""
if cfg_out="$("${CLI[@]}" configure-pair --request-id "cfg-${TOKEN}-off" --pair zcash --direction "$DIRECTION_CLI" \
      --enabled false --price-source local --minimum-foreign-units "$FOREIGN_UNITS" \
      --maximum-foreign-units "$FOREIGN_UNITS" --offer-ttl-seconds "$TTL" 2>&1)"; then
  on_rev=1
else
  rev="$(grep -oE 'actual Some\([0-9]+\)' <<<"$cfg_out" | grep -oE '[0-9]+' || true)"
  [[ -n "$rev" ]] || { printf '%s\n' "$cfg_out" >&2; exit 1; }
  "${CLI[@]}" configure-pair --request-id "cfg-${TOKEN}-off2" --expected-revision "$rev" --pair zcash \
    --direction "$DIRECTION_CLI" --enabled false --price-source local \
    --minimum-foreign-units "$FOREIGN_UNITS" --maximum-foreign-units "$FOREIGN_UNITS" \
    --offer-ttl-seconds "$TTL" >/dev/null
  on_rev=$((rev + 1))
fi
price_rev=""
if ! price_out="$("${CLI[@]}" set-local-price --request-id "price-${TOKEN}" --pair zcash --direction "$DIRECTION_CLI" \
      --lez-units-per-lot 5 --foreign-units-per-lot 2 2>&1)"; then
  price_rev="$(grep -oE 'actual Some\([0-9]+\)' <<<"$price_out" | grep -oE '[0-9]+' || true)"
  [[ -n "$price_rev" ]] || { printf '%s\n' "$price_out" >&2; exit 1; }
  "${CLI[@]}" set-local-price --request-id "price-${TOKEN}2" --expected-revision "$price_rev" --pair zcash \
    --direction "$DIRECTION_CLI" --lez-units-per-lot 5 --foreign-units-per-lot 2 >/dev/null
fi
"${CLI[@]}" configure-pair --request-id "cfg-${TOKEN}-on" --expected-revision "$on_rev" --pair zcash \
  --direction "$DIRECTION_CLI" --enabled true --price-source local \
  --minimum-foreign-units "$FOREIGN_UNITS" --maximum-foreign-units "$FOREIGN_UNITS" \
  --offer-ttl-seconds "$TTL" >/dev/null
"${CLI[@]}" publish-offer --request-id "pub-${TOKEN}" --offer-id "$OFFER_ID" \
  --pair zcash --direction "$DIRECTION_CLI" >/dev/null
log "offer ${OFFER_ID} published"

# ---------------------------------------------------- 4. discovery + draft
log "discovering the signed offer and preparing the taker draft"
MAKER_KEY="$(compose run --rm --no-deps --entrypoint bash maker-node -c \
  '/usr/local/bin/lez-maker-cli delivery-identity --signing-key-file /var/lib/lez/maker/delivery-signing.key | tr -d " \n" | grep -o "02[0-9a-f]\{64\}\|03[0-9a-f]\{64\}"')"
DISCOVERY="$(compose run --rm --no-deps --entrypoint bash maker-node -c "
  /usr/local/bin/lez-taker-cli --delivery-directory /delivery --maker-public-key ${MAKER_KEY} \
    --now-unix-seconds \$(date -u +%s) --pair zcash --direction ${DIRECTION_CLI}")"
COMMITMENT="$(jq -er --arg offer "$OFFER_ID" '.offers[] | select(.offer.id == $offer) | .signed_envelope_sha256' <<<"$DISCOVERY")"
EXPIRES="$(jq -er --arg offer "$OFFER_ID" '.offers[] | select(.offer.id == $offer) | .offer.expires_at_unix_seconds' <<<"$DISCOVERY")"
SIGNED_ENVELOPE="/delivery/${OFFER_ID}.offer.json"
NOW="$(date -u +%s)"
compose run --rm --no-deps --entrypoint bash maker-node -c "
set -e
/usr/local/bin/zec-local-poc-chat-draft \
  --source-agreement-file ${AGREEMENT} \
  --now-unix-seconds ${NOW} --reservation-id ${RESERVATION_ID} \
  --offer-commitment ${COMMITMENT} \
  --offer-expires-at-unix-seconds ${EXPIRES} \
  --output-file /prep/${TOKEN}/unsigned-draft.borsh >/dev/null
" >/dev/null
log "draft bound to offer commitment ${COMMITMENT:0:16}…"

# ------------------------------------------- 5. registry + service config
log "writing the Taker Node prepared configuration"
compose run --rm --no-deps --entrypoint bash \
  -v lez-prep-state:/prep -v lez-taker-state:/t -v lez-delivery-dir:/delivery maker-node -c "
set -e
mkdir -p /t/registry && chmod 700 /t/registry
REG=/t/registry/node.sqlite3
rm -f \"\$REG\" \"\$REG-wal\" \"\$REG-shm\" \"\$REG-journal\"
/usr/local/bin/lez-taker-registry-init --database \"\$REG\" >/dev/null
jq -n \
  --arg maker '${MAKER_KEY}' --arg chat /run/lez/maker/chat.sock \
  --arg registry /var/lib/lez/taker/registry/node.sqlite3 --arg swap '${SWAP_ID}' --arg offer '${OFFER_ID}' \
  --arg reservation '${RESERVATION_ID}' \
  --arg envelope '${SIGNED_ENVELOPE}' --arg envelope_sha '${COMMITMENT}' \
  --arg draft /prep/${TOKEN}/unsigned-draft.borsh \
  --arg draft_sha \"\$(sha256sum /prep/${TOKEN}/unsigned-draft.borsh | cut -d' ' -f1)\" \
  --arg key /prep/${TOKEN}/actors/taker/zcash.key \
  --arg src /prep/${TOKEN}/actors/taker/actor-config.json \
  --arg src_sha \"\$(sha256sum /prep/${TOKEN}/actors/taker/actor-config.json | cut -d' ' -f1)\" \
  --arg agreement /prep/${TOKEN}/final-agreement.borsh \
  --arg actor_root /prep/${TOKEN}/taker-actors \
  --arg receipt /prep/${TOKEN}/acceptance-receipt.json \
  '{schema_version:1,
    delivery_sources:[{source_id:\"local-maker\", directory:\"/delivery\", maker_public_key:\$maker}],
    chat_socket:\$chat, maximum_offers:1024,
    initiation:{execute_prepared_zec:true, registry_database:\$registry,
      prepared_zec:[{source_id:\"local-maker\", swap_id:\$swap, offer_id:\$offer,
        reservation_id:\$reservation, foreign_units:${FOREIGN_UNITS}, lez_units:${LEZ_UNITS},
        signed_envelope:{path:\$envelope, sha256:\$envelope_sha},
        unsigned_draft:{path:\$draft, sha256:\$draft_sha},
        signing_key:{path:\$key},
        source_config:{path:\$src, sha256:\$src_sha},
        agreement_output:\$agreement, actor_root:\$actor_root, receipt_output:\$receipt}]}}' \
  > /t/role.json
chmod 0600 /t/role.json
" >/dev/null

compose stop taker-node >/dev/null
compose up -d taker-node >/dev/null
taker_ready=0
for i in $(seq 1 40); do
  if compose exec -T taker-node curl -sf --max-time 2 --unix-socket /run/lez/taker/node.sock \
      --header 'content-type: application/json' \
      --data '{"jsonrpc":"2.0","id":1,"method":"taker_health","params":[{"schema_version":1}]}' \
      http://localhost/ >/dev/null 2>&1; then
    taker_ready=1
    break
  fi
  sleep 1
done
[[ "$taker_ready" == 1 ]] || { compose logs --tail 40 taker-node >&2; exit 1; }

cat <<BANNER

──────────────────────────────────────────────────────────────
 Optional prepared ZEC service lane is armed (token ${TOKEN})

 In Basecamp (VNC :5901), LEZ / BTC Taker → advanced prepared corridor:
   1. pair: Zcash, direction: TakerSellsLez
   2. Browse authenticated offers — newest offer auto-selected:
      ${OFFER_ID}
   3. Review the filled exact terms, then press "Confirm and initiate"
      — REAL Chat acceptance runs
   4. The current swap card tracks state NotActivated

 replay-safe: repeat the identical click to see was_replay
──────────────────────────────────────────────────────────────
BANNER
