[package]
name = "lez-xmr-monero-adapter"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "=1.0.103"
async-trait = "=0.1.89"
diqwest = { version = "=3.1.0", default-features = false }
lez-bridge-protocol = { version = "0.1.0", path = "../lez-bridge-protocol" }
lez-xmr-swap-sdk = { version = "0.1.0", path = "../xmr-swap-sdk" }
monero-rpc = { version = "=0.5.1", default-features = false, features = ["rpc_authentication"] }
reqwest = { version = "=0.12.28", default-features = false }
serde = { version = "=1.0.228", features = ["derive"] }
serde_json = "=1.0.150"
thiserror = "=2.0.18"
url = "=2.5.8"

[dev-dependencies]
digest_auth = { version = "=0.3.1", default-features = false }
static_assertions = "=1.1.0"
tokio = { version = "=1.52.3", features = ["io-util", "macros", "net", "rt", "sync"] }

[lints]
workspace = true
