"use strict";
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
let toastTimer;
function toast(message) { const node = $("#toast"); if (!node) return; node.textContent = message; node.classList.add("show"); clearTimeout(toastTimer); toastTimer = setTimeout(() => node.classList.remove("show"), 2400); }
function showView(id) { $$(".app-view").forEach((view) => view.classList.toggle("active", view.id === id)); $$("[data-view]").forEach((button) => button.classList.toggle("active", button.dataset.view === id)); const view = document.getElementById(id); const heading = view?.querySelector("h1"); if (heading) heading.focus?.({ preventScroll: true }); window.scrollTo({ top: 0, behavior: "smooth" }); }
$$('[data-view], [data-view-jump]').forEach((button) => button.addEventListener("click", () => showView(button.dataset.view || button.dataset.viewJump)));
const makerSwaps = [
  { id:"ZEC-7F2A", pair:"LEZ / ZEC", state:"Awaiting confirmation", status:"wait", progress:"1 / 2 confirmations", amount:"1,820 LEZ → 2.00 ZEC", action:"Claim" },
  { id:"BTC-3BD1", pair:"LEZ / BTC", state:"Counterparty locked", status:"good", progress:"Ready to drive", amount:"7,700 LEZ → 0.005 BTC", action:"Drive" }
];
const makerHistory = [
  { id:"XMR-DA82", pair:"LEZ / XMR", route:"Maker sold LEZ", outcome:"Completed", amount:"4,240 LEZ", time:"Today 18:42" },
  { id:"BTC-19C4", pair:"LEZ / BTC", route:"Maker sold BTC", outcome:"Refunded", amount:"0.004 BTC", time:"Yesterday 09:14" },
  { id:"ZEC-51AF", pair:"LEZ / ZEC", route:"Maker sold LEZ", outcome:"Completed", amount:"910 LEZ", time:"Jul 31 16:07" }
];
function swapCard(swap, active = false) { return `<button class="swap-card${active ? " active" : ""}" type="button" data-swap="${swap.id}"><header><strong>${swap.id}</strong><span class="tag ${swap.status === "good" ? "good-tag" : "wait-tag"}">${swap.state}</span></header><p>${swap.pair}</p><small>${swap.amount}</small></button>`; }
function renderMaker() {
  const overview = $("#overview-swap-list"); if (overview) overview.innerHTML = makerSwaps.map((s) => `<div class="swap-row"><div><strong>${s.id} · ${s.pair}</strong><br><small>${s.amount}</small></div><span class="tag ${s.status === "good" ? "good-tag" : "wait-tag"}">${s.state}</span></div>`).join("");
  const list = $("#active-swap-list"); if (list) { list.innerHTML = makerSwaps.map((s, index) => swapCard(s, index === 0)).join(""); list.addEventListener("click", (event) => { const card = event.target.closest("[data-swap]"); if (!card) return; $$(".swap-card", list).forEach((node) => node.classList.toggle("active", node === card)); renderMakerDetail(makerSwaps.find((s) => s.id === card.dataset.swap)); }); }
  renderMakerDetail(makerSwaps[0]); renderHistory();
}
function renderMakerDetail(swap) { const detail = $("#maker-swap-detail"); if (!detail || !swap) return; detail.innerHTML = `<div class="eyebrow">Secret-free sample projection</div><h2>${swap.id}</h2><dl class="detail-list"><div><dt>Pair</dt><dd>${swap.pair}</dd></div><div><dt>State</dt><dd>${swap.state}</dd></div><div><dt>Progress</dt><dd>${swap.progress}</dd></div><div><dt>Amount</dt><dd>${swap.amount}</dd></div><div><dt>Next semantic action</dt><dd>${swap.action}</dd></div></dl><div class="notice compact"><span class="notice-icon">P</span><div>Buttons below change sample browser state only.</div></div><div class="history-actions"><button class="button secondary" data-maker-action="claim" type="button">Request sample claim</button><button class="button danger-secondary" data-maker-action="refund" type="button">Request sample refund</button></div>`; $$('[data-maker-action]', detail).forEach((button) => button.addEventListener("click", () => toast(`Sample ${button.dataset.makerAction} intent recorded for ${swap.id}; no daemon call.`))); }
function renderHistory() { const body = $("#history-body"); if (!body) return; const query = ($("#history-search")?.value || "").toLowerCase(); const filter = $("#history-filter")?.value || "all"; const rows = makerHistory.filter((row) => (filter === "all" || row.outcome.toLowerCase() === filter) && `${row.id} ${row.pair}`.toLowerCase().includes(query)); body.innerHTML = rows.length ? rows.map((r) => `<tr><td>${r.id}</td><td>${r.pair}</td><td>${r.route}</td><td><span class="tag ${r.outcome === "Completed" ? "good-tag" : "neutral-tag"}">${r.outcome}</span></td><td>${r.amount}</td><td>${r.time}</td></tr>`).join("") : `<tr><td colspan="6">No sample records match.</td></tr>`; }
function setupMaker() {
  renderMaker(); $("#history-search")?.addEventListener("input", renderHistory); $("#history-filter")?.addEventListener("change", renderHistory);
  $("#export-sample")?.addEventListener("click", () => toast("Sample export previewed in memory; no file was written."));
  const updatePrice = () => { const pair = $("#maker-pair"); const unit = pair?.selectedOptions[0].text.replace("LEZ / ", "") || "asset"; const symbol = { Bitcoin:"BTC", Monero:"XMR", Zcash:"ZEC" }[unit] || unit; const foreign = Number($("#foreign-units")?.value || 0); const lez = Number($("#lez-units")?.value || 0); $("#maker-price-preview").textContent = `${foreign.toLocaleString()} ${symbol} = ${lez.toLocaleString()} LEZ`; };
  ["#maker-pair","#foreign-units","#lez-units"].forEach((selector) => $(selector)?.addEventListener("input", updatePrice));
  $("#maker-config-form")?.addEventListener("reset", () => setTimeout(updatePrice));
  $("#maker-config-form")?.addEventListener("submit", (event) => { event.preventDefault(); $("#maker-review-content").innerHTML = `<dl class="detail-list"><div><dt>Pair</dt><dd>${$("#maker-pair").selectedOptions[0].text}</dd></div><div><dt>Direction</dt><dd>${$("#maker-direction").selectedOptions[0].text}</dd></div><div><dt>Price</dt><dd>${$("#maker-price-preview").textContent}</dd></div></dl>`; $("#maker-review-dialog").showModal(); });
  $("#confirm-maker-config")?.addEventListener("click", () => toast("Sample route revision 9 confirmed in browser memory only."));
  $("#maker-refresh")?.addEventListener("click", () => { makerSwaps[0].state = makerSwaps[0].state === "Awaiting confirmation" ? "Claim available" : "Awaiting confirmation"; makerSwaps[0].progress = makerSwaps[0].state === "Claim available" ? "2 / 2 confirmations" : "1 / 2 confirmations"; makerSwaps[0].status = makerSwaps[0].state === "Claim available" ? "good" : "wait"; renderMaker(); toast("Deterministic sample projection advanced; no RPC was opened."); });
}
const offers = [
  { id:"offer-zec-7f2a", asset:"ZEC", icon:"Z", cls:"zec", pair:"LEZ / ZEC", receive:"2.00 ZEC", send:"1,820 LEZ", rate:"1 ZEC = 910 LEZ", direction:"receive-foreign", maker:"Maker 7E4C", expiry:"12:42" },
  { id:"offer-btc-3bd1", asset:"BTC", icon:"₿", cls:"btc", pair:"LEZ / BTC", receive:"0.005 BTC", send:"7,700 LEZ", rate:"1 BTC = 1,540,000 LEZ", direction:"receive-foreign", maker:"Maker A91D", expiry:"08:19" },
  { id:"offer-xmr-da82", asset:"XMR", icon:"ɱ", cls:"xmr", pair:"LEZ / XMR", receive:"1.00 XMR", send:"4,240 LEZ", rate:"1 XMR = 4,240 LEZ", direction:"receive-foreign", maker:"Maker 18BF", expiry:"19:03" },
  { id:"offer-lez-51af", asset:"ZEC", icon:"Z", cls:"zec", pair:"ZEC / LEZ", receive:"9,100 LEZ", send:"10.00 ZEC", rate:"1 ZEC = 910 LEZ", direction:"receive-lez", maker:"Maker C62A", expiry:"14:20" }
];
let offerDirection = "receive-foreign"; let selectedOffer = offers[0]; let progressStep = 1; let terminalIntent = "claim";
const timelineLabels = ["Acceptance receipt persisted", "First lock confirmed", "Counterparty lock finalized", "Terminal action available", "Terminal projection complete"];
function renderOffers() { const query = ($("#offer-search")?.value || "").toLowerCase(); const visible = offers.filter((o) => o.direction === offerDirection && `${o.asset} ${o.pair} ${o.maker}`.toLowerCase().includes(query)); $("#offer-grid").innerHTML = visible.length ? visible.map((o) => `<article class="offer-card"><header><span class="asset-icon ${o.cls}">${o.icon}</span><span class="tag good-tag">Sample signed</span></header><div><div class="eyebrow">${o.pair}</div><h2>Receive ${o.receive}</h2></div><dl><div><dt>You send</dt><dd>${o.send}</dd></div><div><dt>Sample rate</dt><dd>${o.rate}</dd></div><div><dt>Maker identity</dt><dd>${o.maker}</dd></div><div><dt>Expires</dt><dd>${o.expiry}</dd></div></dl><button class="button primary full" type="button" data-offer="${o.id}">Review exact terms</button></article>`).join("") : `<div class="notice"><span class="notice-icon">i</span><div>No deterministic sample offers match.</div></div>`; $$('[data-offer]').forEach((button) => button.addEventListener("click", () => selectOffer(offers.find((o) => o.id === button.dataset.offer)))); }
function selectOffer(offer) { if (!offer) return; selectedOffer = offer; $("#selected-offer-detail").innerHTML = `<div class="eyebrow">${offer.maker}</div><h2>${offer.pair}</h2><div class="swap-hero"><div class="asset-pair"><span class="asset-icon lez">L</span><span class="pair-line">⇄</span><span class="asset-icon ${offer.cls}">${offer.icon}</span></div><div><small>You send</small><strong>${offer.send}</strong></div><div><small>You receive</small><strong>${offer.receive}</strong></div></div><dl class="detail-list"><div><dt>Exact sample price</dt><dd>${offer.rate}</dd></div><div><dt>Maker identity</dt><dd>${offer.maker}</dd></div><div><dt>Recovery window</dt><dd>38 sample minutes</dd></div><div><dt>Offer ID</dt><dd>${offer.id}</dd></div></dl>`; $("#terms-confirm").checked = false; $("#initiate-swap").disabled = true; showView("taker-review"); }
function renderTimeline() { $("#swap-timeline").innerHTML = timelineLabels.map((label, index) => `<li class="${index <= progressStep ? "done" : ""}"><span>${label}</span></li>`).join(""); const terminal = $("#terminal-actions"); if (terminal) terminal.hidden = progressStep < 3; $("#progress-description").textContent = progressStep < 3 ? `Deterministic step ${progressStep + 1} of 4; role receipt remains the sample authority.` : "The sample role may now choose one mutually exclusive terminal action."; }
function syncProgressOffer() { const shortId = selectedOffer.id.replace("offer-", "").toUpperCase(); $("#progress-short-id").textContent = shortId; $("#progress-receive").textContent = selectedOffer.receive; $("#progress-asset-icon").textContent = selectedOffer.icon; $("#progress-asset-icon").className = `asset-icon ${selectedOffer.cls}`; $("#aside-pair").textContent = selectedOffer.pair; $("#initiate-summary").innerHTML = `<strong>${selectedOffer.pair}</strong><br>${selectedOffer.send} → ${selectedOffer.receive}<br><small>${selectedOffer.maker}</small>`; }
function setupTaker() {
  renderOffers(); syncProgressOffer(); renderTimeline();
  $("#offer-search")?.addEventListener("input", renderOffers); $$("[data-direction]").forEach((button) => button.addEventListener("click", () => { offerDirection = button.dataset.direction; $$("[data-direction]").forEach((node) => node.classList.toggle("active", node === button)); renderOffers(); }));
  $("#terms-confirm")?.addEventListener("change", (event) => { $("#initiate-swap").disabled = !event.target.checked; });
  $("#initiate-swap")?.addEventListener("click", () => { syncProgressOffer(); $("#initiate-dialog").showModal(); });
  $("#confirm-initiate")?.addEventListener("click", () => { progressStep = 1; renderTimeline(); showView("taker-progress"); toast("Private sample receipt created in browser memory; no negotiation occurred."); });
  $("#advance-progress")?.addEventListener("click", () => { progressStep = Math.min(3, progressStep + 1); renderTimeline(); $("#aside-confirmations").textContent = progressStep >= 2 ? "2 / 2 sample" : "1 / 2 sample"; toast("Deterministic sample advanced without chain or wallet access."); });
  ["claim","refund"].forEach((intent) => $(`#${intent}-action`)?.addEventListener("click", () => { terminalIntent = intent; $("#terminal-dialog-title").textContent = `${intent[0].toUpperCase() + intent.slice(1)} sample funds?`; $("#terminal-dialog-copy").textContent = `The production role would admit one generation-fenced ${intent} intent. This only changes browser sample state.`; $("#confirm-terminal").textContent = `Confirm sample ${intent}`; $("#terminal-dialog").showModal(); }));
  $("#confirm-terminal")?.addEventListener("click", () => { progressStep = 4; $("#terminal-heading").textContent = terminalIntent === "claim" ? "Swap completed" : "Swap refunded"; $("#terminal-summary").textContent = `The sample ${terminalIntent} path reached its terminal projection. No funds moved.`; $("#shield-guidance").hidden = !(terminalIntent === "claim" && selectedOffer.asset === "ZEC" && selectedOffer.direction === "receive-foreign"); showView("taker-terminal"); toast(`Sample ${terminalIntent} completed; no chain command ran.`); });
  $("#shield-checklist")?.addEventListener("click", (event) => { event.currentTarget.textContent = "Guidance reviewed in this sample"; event.currentTarget.disabled = true; });
}
const role = document.body.dataset.prototype; if (role === "maker") setupMaker(); if (role === "taker") setupTaker();
